id = "logos"
name = "Logos"
version = "0.0.1"
schema_version = 1
authors = ["Great Love <68994918+nobottomline@users.noreply.github.com>"]
description = "Syntax highlighting for Theos Logos .x and .xm files."
repository = "https://github.com/nobottomline/logos-zed"

[grammars.logos]
repository = "https://github.com/nobottomline/logos-zed"
rev = "main"
